sudo: false
language: python
python:
  -3.5
  -3.6
  -3.7
  mextrix:
    include:
      -python: 3.7
      dist: xenial # required for python 3.7
      sudo: true # required for python 3.7
  install:
    - pip install poetry
    - poetry install -vvv
  script:
    -poetry run coverage run --source=apiteseting -m pytest -v
    -poetry run coverage report -m
  after_success:
    - poetry run coveralls